POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1c3NpbmllbWkiLCJpZCI6IjYyZjVlNTIzNTAwZWU1NTc4YThjOWNkNiIsImlhdCI6MTY2MDM3MjAwOX0.lKEdYLCdFd8KZIMe3yDgxRYKe6E0p74DYPcDb_lHj58

{
    "title": "testi backista taaseeeen middleware erotettu ja user.request",
    "author": "Jussi",
    "url": "sample.com/blog",
    "likes": 0
}